//package com.example.dataconfig;
//
//import java.io.Serializable;
//import java.util.Date;
//import java.util.List;
//
///**
// *
// * This class was generated by MyBatis Generator.
// * This class corresponds to the database table tj_admin
// *
// * @mbg.generated do_not_delete_during_merge
// */
//public class TjAdmin implements Serializable {
//    private List<String> authorityList;
//    private String bTime;
//    private String eTime;
//    private String updateName;//修改人姓名
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.admin_id
//     *
//     * @mbg.generated
//     */
//    private Integer adminId;
//
//    /**
//     * Database Column Remarks:
//     *   用户登录名称
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.user_name
//     *
//     * @mbg.generated
//     */
//    private String userName;
//
//    /**
//     * Database Column Remarks:
//     *   密码，md5两次加密
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.password
//     *
//     * @mbg.generated
//     */
//    private String password;
//
//    /**
//     * Database Column Remarks:
//     *   电话号码
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.phone
//     *
//     * @mbg.generated
//     */
//    private String phone;
//
//    /**
//     * Database Column Remarks:
//     *   邮箱
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.email
//     *
//     * @mbg.generated
//     */
//    private String email;
//
//    /**
//     * Database Column Remarks:
//     *   删除状态 【0：否 1：是】
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.deleted
//     *
//     * @mbg.generated
//     */
//    private Boolean deleted;
//
//    /**
//     * Database Column Remarks:
//     *   创建时间
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.create_time
//     *
//     * @mbg.generated
//     */
//    private Date createTime;
//
//    /**
//     * Database Column Remarks:
//     *   更新时间
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.update_time
//     *
//     * @mbg.generated
//     */
//    private Date updateTime;
//
//    /**
//     * Database Column Remarks:
//     *   操作人
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.creater
//     *
//     * @mbg.generated
//     */
//    private Integer creater;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column tj_admin.updater
//     *
//     * @mbg.generated
//     */
//    private Integer updater;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table tj_admin
//     *
//     * @mbg.generated
//     */
//    private static final long serialVersionUID = 1L;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.admin_id
//     *
//     * @return the value of tj_admin.admin_id
//     *
//     * @mbg.generated
//     */
//    public Integer getAdminId() {
//        return adminId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.admin_id
//     *
//     * @param adminId the value for tj_admin.admin_id
//     *
//     * @mbg.generated
//     */
//    public void setAdminId(Integer adminId) {
//        this.adminId = adminId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.user_name
//     *
//     * @return the value of tj_admin.user_name
//     *
//     * @mbg.generated
//     */
//    public String getUserName() {
//        return userName;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.user_name
//     *
//     * @param userName the value for tj_admin.user_name
//     *
//     * @mbg.generated
//     */
//    public void setUserName(String userName) {
//        this.userName = userName == null ? null : userName.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.password
//     *
//     * @return the value of tj_admin.password
//     *
//     * @mbg.generated
//     */
//    public String getPassword() {
//        return password;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.password
//     *
//     * @param password the value for tj_admin.password
//     *
//     * @mbg.generated
//     */
//    public void setPassword(String password) {
//        this.password = password == null ? null : password.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.phone
//     *
//     * @return the value of tj_admin.phone
//     *
//     * @mbg.generated
//     */
//    public String getPhone() {
//        return phone;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.phone
//     *
//     * @param phone the value for tj_admin.phone
//     *
//     * @mbg.generated
//     */
//    public void setPhone(String phone) {
//        this.phone = phone == null ? null : phone.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.email
//     *
//     * @return the value of tj_admin.email
//     *
//     * @mbg.generated
//     */
//    public String getEmail() {
//        return email;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.email
//     *
//     * @param email the value for tj_admin.email
//     *
//     * @mbg.generated
//     */
//    public void setEmail(String email) {
//        this.email = email == null ? null : email.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.deleted
//     *
//     * @return the value of tj_admin.deleted
//     *
//     * @mbg.generated
//     */
//    public Boolean getDeleted() {
//        return deleted;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.deleted
//     *
//     * @param deleted the value for tj_admin.deleted
//     *
//     * @mbg.generated
//     */
//    public void setDeleted(Boolean deleted) {
//        this.deleted = deleted;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.create_time
//     *
//     * @return the value of tj_admin.create_time
//     *
//     * @mbg.generated
//     */
//    public Date getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.create_time
//     *
//     * @param createTime the value for tj_admin.create_time
//     *
//     * @mbg.generated
//     */
//    public void setCreateTime(Date createTime) {
//        this.createTime = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.update_time
//     *
//     * @return the value of tj_admin.update_time
//     *
//     * @mbg.generated
//     */
//    public Date getUpdateTime() {
//        return updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.update_time
//     *
//     * @param updateTime the value for tj_admin.update_time
//     *
//     * @mbg.generated
//     */
//    public void setUpdateTime(Date updateTime) {
//        this.updateTime = updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.creater
//     *
//     * @return the value of tj_admin.creater
//     *
//     * @mbg.generated
//     */
//    public Integer getCreater() {
//        return creater;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.creater
//     *
//     * @param creater the value for tj_admin.creater
//     *
//     * @mbg.generated
//     */
//    public void setCreater(Integer creater) {
//        this.creater = creater;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column tj_admin.updater
//     *
//     * @return the value of tj_admin.updater
//     *
//     * @mbg.generated
//     */
//    public Integer getUpdater() {
//        return updater;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column tj_admin.updater
//     *
//     * @param updater the value for tj_admin.updater
//     *
//     * @mbg.generated
//     */
//    public void setUpdater(Integer updater) {
//        this.updater = updater;
//    }
//
//    public List<String> getAuthorityList() {
//        return authorityList;
//    }
//
//    public void setAuthorityList(List<String> authorityList) {
//        this.authorityList = authorityList;
//    }
//
//
//
//    public String getUpdateName() {
//        return updateName;
//    }
//
//    public void setUpdateName(String updateName) {
//        this.updateName = updateName;
//    }
//
//    public String getbTime() {
//        return bTime;
//    }
//
//    public void setbTime(String bTime) {
//        this.bTime = bTime;
//    }
//
//    public String geteTime() {
//        return eTime;
//    }
//
//    public void seteTime(String eTime) {
//        this.eTime = eTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tj_admin
//     *
//     * @mbg.generated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", adminId=").append(adminId);
//        sb.append(", userName=").append(userName);
//        sb.append(", password=").append(password);
//        sb.append(", phone=").append(phone);
//        sb.append(", email=").append(email);
//        sb.append(", deleted=").append(deleted);
//        sb.append(", createTime=").append(createTime);
//        sb.append(", updateTime=").append(updateTime);
//        sb.append(", creater=").append(creater);
//        sb.append(", updater=").append(updater);
//        sb.append(", serialVersionUID=").append(serialVersionUID);
//        sb.append("]");
//        return sb.toString();
//    }
//}
