spring:
  datasource:
    ####写数据源
    update:
      jdbc-url: jdbc:mysql://123.56.152.42:3308/test
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    ###读数据源
    select:
      jdbc-url: jdbc:mysql://123.56.152.42:3306/test
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 1
    host: 123.56.152.42
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  data:
    mongodb:
      uri: mongodb://123.56.152.42:27017/app