spring:
  datasource:
    ####写数据源
    update:
      jdbc-url: jdbc:mysql://123.56.152.42:3308/test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    ###读数据源
    select:
      jdbc-url: jdbc:mysql://123.56.152.42:3306/test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

