package com.example.operationlog;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table system_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SystemLog implements Serializable {
    /**
     * Database Column Remarks:
     *   操作日志id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_id
     *
     * @mbg.generated
     */
    private Long slId;

    /**
     * Database Column Remarks:
     *   操作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_operate
     *
     * @mbg.generated
     */
    private String slOperate;

    /**
     * Database Column Remarks:
     *   模块名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_operate_name
     *
     * @mbg.generated
     */
    private String slOperateName;

    /**
     * Database Column Remarks:
     *   操作内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_content
     *
     * @mbg.generated
     */
    private String slContent;

    /**
     * Database Column Remarks:
     *   请求参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_params
     *
     * @mbg.generated
     */
    private String slParams;

    /**
     * Database Column Remarks:
     *   操作者ip地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.sl_ip
     *
     * @mbg.generated
     */
    private String slIp;

    /**
     * Database Column Remarks:
     *   管理员外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.fk_au_id
     *
     * @mbg.generated
     */
    private Long fkAuId;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.operate_time
     *
     * @mbg.generated
     */
    private Date operateTime;

    /**
     * 查询开始时间
     */
    private Date beginDate;

    /**
     * 查询结束时间
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_id
     *
     * @return the value of system_log.sl_id
     *
     * @mbg.generated
     */
    public Long getSlId() {
        return slId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_id
     *
     * @param slId the value for system_log.sl_id
     *
     * @mbg.generated
     */
    public void setSlId(Long slId) {
        this.slId = slId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_operate
     *
     * @return the value of system_log.sl_operate
     *
     * @mbg.generated
     */
    public String getSlOperate() {
        return slOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_operate
     *
     * @param slOperate the value for system_log.sl_operate
     *
     * @mbg.generated
     */
    public void setSlOperate(String slOperate) {
        this.slOperate = slOperate == null ? null : slOperate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_operate_name
     *
     * @return the value of system_log.sl_operate_name
     *
     * @mbg.generated
     */
    public String getSlOperateName() {
        return slOperateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_operate_name
     *
     * @param slOperateName the value for system_log.sl_operate_name
     *
     * @mbg.generated
     */
    public void setSlOperateName(String slOperateName) {
        this.slOperateName = slOperateName == null ? null : slOperateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_content
     *
     * @return the value of system_log.sl_content
     *
     * @mbg.generated
     */
    public String getSlContent() {
        return slContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_content
     *
     * @param slContent the value for system_log.sl_content
     *
     * @mbg.generated
     */
    public void setSlContent(String slContent) {
        this.slContent = slContent == null ? null : slContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_params
     *
     * @return the value of system_log.sl_params
     *
     * @mbg.generated
     */
    public String getSlParams() {
        return slParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_params
     *
     * @param slParams the value for system_log.sl_params
     *
     * @mbg.generated
     */
    public void setSlParams(String slParams) {
        this.slParams = slParams == null ? null : slParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.sl_ip
     *
     * @return the value of system_log.sl_ip
     *
     * @mbg.generated
     */
    public String getSlIp() {
        return slIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.sl_ip
     *
     * @param slIp the value for system_log.sl_ip
     *
     * @mbg.generated
     */
    public void setSlIp(String slIp) {
        this.slIp = slIp == null ? null : slIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.fk_au_id
     *
     * @return the value of system_log.fk_au_id
     *
     * @mbg.generated
     */
    public Long getFkAuId() {
        return fkAuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.fk_au_id
     *
     * @param fkAuId the value for system_log.fk_au_id
     *
     * @mbg.generated
     */
    public void setFkAuId(Long fkAuId) {
        this.fkAuId = fkAuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.operate_time
     *
     * @return the value of system_log.operate_time
     *
     * @mbg.generated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.operate_time
     *
     * @param operateTime the value for system_log.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("SystemLog{");
        sb.append("slId=").append(slId);
        sb.append(", slOperate='").append(slOperate).append('\'');
        sb.append(", slOperateName='").append(slOperateName).append('\'');
        sb.append(", slContent='").append(slContent).append('\'');
        sb.append(", slParams='").append(slParams).append('\'');
        sb.append(", slIp='").append(slIp).append('\'');
        sb.append(", fkAuId=").append(fkAuId);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", beginDate=").append(beginDate);
        sb.append(", endDate=").append(endDate);
        sb.append('}');
        return sb.toString();
    }
}
